// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEKG4dy99jnsRPjOzcllKagSdKHKx-6nE',
    appId: '1:789872418575:ios:0e26771cc2df04538ae87a',
    messagingSenderId: '789872418575',
    projectId: 'smart-resource-app-fffe7',
    storageBucket: 'smart-resource-app-fffe7.firebasestorage.app',
    iosBundleId: 'com.example.smartResourceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEKG4dy99jnsRPjOzcllKagSdKHKx-6nE',
    appId: '1:789872418575:ios:0e26771cc2df04538ae87a',
    messagingSenderId: '789872418575',
    projectId: 'smart-resource-app-fffe7',
    storageBucket: 'smart-resource-app-fffe7.firebasestorage.app',
    iosBundleId: 'com.example.smartResourceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNf1iGclwfVyyHPFra60g2Z_HVxvpo4cI',
    appId: '1:789872418575:web:ef0878fc3dc218078ae87a',
    messagingSenderId: '789872418575',
    projectId: 'smart-resource-app-fffe7',
    authDomain: 'smart-resource-app-fffe7.firebaseapp.com',
    storageBucket: 'smart-resource-app-fffe7.firebasestorage.app',
    measurementId: 'G-8ZX25KEGY4',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNf1iGclwfVyyHPFra60g2Z_HVxvpo4cI',
    appId: '1:789872418575:web:ef0878fc3dc218078ae87a',
    messagingSenderId: '789872418575',
    projectId: 'smart-resource-app-fffe7',
    authDomain: 'smart-resource-app-fffe7.firebaseapp.com',
    storageBucket: 'smart-resource-app-fffe7.firebasestorage.app',
    measurementId: 'G-8ZX25KEGY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGdmL0cgncabEuZAbM0vb-Kr0g82t-AeE',
    appId: '1:789872418575:android:11cbcfa1aa62d0d38ae87a',
    messagingSenderId: '789872418575',
    projectId: 'smart-resource-app-fffe7',
    storageBucket: 'smart-resource-app-fffe7.firebasestorage.app',
  );

}